# Generated by Django 3.1.5 on 2021-01-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=64, verbose_name='아이디')),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('gender', models.CharField(choices=[('M', '남성(MAN)'), ('W', '여성(Woman)')], max_length=1, verbose_name='성별')),
                ('registered', models.DateTimeField(auto_now_add=True, verbose_name='등록')),
            ],
        ),
    ]
